### PR TITLE
Make (Section/Flat)Grids allow delegated props on TS

### LINKED ISSUE #95: [TS] Missing  some props described on readme
As stated on the readme:
> All additional props you pass will be passed on to the internal FlatList/SectionList. This means you can make use of various props and methods like ListHeaderComponent, onEndReached, onRefresh...etc. While these are not tested for compatibility, most of them should work as expected.

But the declaration file actually doesn't merge the `FlatList ` or the `SectionListProps` on the declarations, this could be solved by this:

```typescript
import {
  ...others,
  FlatListProps, 
  SectionListProps
} from 'react-native'

// Older ts versions don't have this type
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;

type FlatListAllowedProps<ItemType = any> = Omit<FlatListProps<ItemType>,
  | 'data'
  | 'someOtherPropNotAllowed'
>

/**
 * React Native Super Grid Properties
 */
export interface FlatGridProps<ItemType = any> extends FlatListAllowedProps<ItemType> {
...rest

// Same for section
```

I'm not openning a PR cuz this may be wrong, I'm not sure if the props should be exactly the same, it's likely that the grid/section overide some props, but i don't know exacly which ones

### PR DESCRIPTION
**Pull request by Grohden**
Extended the SectionGrid and FlatGrid props declarations from the original declarations,
I've also fixed a type issue with SectionGrid prop `sections`, that was declared as a single item instead of list

This should close #95

### CODE REVIEW

**Comment by Grohden** [comment]
I've made the changes based on the readme, I pasted them on my project and they seem fine. But still I would like a confirmation from the author that I omited all the overriden/changed props from the original components

**Comment by Grohden** [comment]
Looking at the readme again, shouldn't the `sections` prop be declared as:
```typescript

export type SectionItem<ItemType> = {
   title: string;
   data: ItemType[];
}

// ...declarations
sections:  SectionItem<ItemType>[];
//...declarations
```
?
Also, not sure, but sections may contain different items for their lists.. but probably TS will infer a union for the data prop of the section item

File: index.d.ts [hunk 1]
```diff
@@ -6,12 +6,23 @@ import {
...
+type FlatListAllowedProps<ItemType = any> = Omit<FlatListProps<ItemType>,
+  | "data"
+  | "renderItem"
+>
 
 /**
  * React Native Super Grid Properties
  */
-export interface FlatGridProps<ItemType = any> {
+export interface FlatGridProps<ItemType = any> extends FlatListAllowedProps<ItemType> {
```
Comment (saleel) [inline index.d.ts]: If we can extend from FlatListProps then there is no need to explicitly mention props like `ListEmptyComponent`, `onEndReached`...etc here

**Comment by saleel** [comment]
> Looking at the readme again, shouldn't the `sections` prop be declared as:
> 
> ```ts
> export type SectionItem<ItemType> = {
>    title: string;
>    data: ItemType[];
> }
> 
> // ...declarations
> sections:  SectionItem<ItemType>[];
> //...declarations
> ```
> 
> ?
> Also, not sure, but sections may contain different items for their lists.. but probably TS will infer a union for the data prop of the section item

This looks correct. Can you also check how they are doing it in the official definition (of SectionList) and update here accordingly. Please test it locally to ensure both SectionGrid and FlatGrid works with the props mentioned in the Readme and the ones provided by FlatList/SectionList

File: index.d.ts (hunk 1 above)
Comment (Grohden) [reply index.d.ts]: I've been reviewing the types now, and there are some diffs that seems wrong to me like:
`keyExtractor?: (item: ItemType[], index: number) => string;` - declared on the super grid
`keyExtractor?: (item: ItemT, index: number) => string;` - declared on the rn grid
I'll keep the RN as a source of truth and remove the types that have the same signature or seems to have a wrong one from the lib

**Comment by Grohden** [comment]
@saleel I've made *some* changes on the types:
* moved common props to a single type
* removed the redeclared props (the ones you mentioned)
* I added the `rowIndex` as a exposed prop on the `renderItem`

I've tested this locally and everything seems fine

**Comment by saleel** [comment]
Merged. Thanks
Will release new version shortly
